config/routes.rb
Rails.application.routes.draw do

  root 'counters#index'

  resources :counters

end

app/models/counter.rb
class Counter < ActiveRecord::Base

  def self.last_said
    last.created_at
  end

  def self.days_since_last_mess_up
    (Date.today - last_said.to_date).to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  before_action :set_counter, only: [:show, :edit, :update, :destroy]

  # GET /counters
  # GET /counters.json
  def index
    @counters = Counter.all
    @counter = Counter.new

    @days_since = Counter.days_since_last_mess_up
  end

  # GET /counters/1
  # GET /counters/1.json
  def show
  end

  # GET /counters/new
  def new
    @counter = Counter.new
  end

  # GET /counters/1/edit
  def edit
  end

  # POST /counters
  # POST /counters.json
  def create
    @counter = Counter.new(counter_params)

    respond_to do |format|
      if @counter.save
        format.html { redirect_to '/counters', notice: 'Counter was successfully reset.' }
        format.json { render :show, status: :created, location: @counter }
      else
        format.html { render :new }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counters/1
  # PATCH/PUT /counters/1.json
  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.html { redirect_to @counter, notice: 'Counter was successfully updated.' }
        format.json { render :show, status: :ok, location: @counter }
      else
        format.html { render :edit }
        format.json { render json: @counter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counters/1
  # DELETE /counters/1.json
  def destroy
    @counter.destroy
    respond_to do |format|
      format.html { redirect_to counters_url, notice: 'Counter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_counter
      @counter = Counter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def counter_params
      params.fetch(:counter, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/counters_helper.rb
module CountersHelper
end

app/views/counters/_form.html.erb
<%= form_for(@counter) do |f| %>
  <% if @counter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@counter.errors.count, "error") %> prohibited this counter from being saved:</h2>

      <ul>
      <% @counter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Someone Messed Up Big Time - Reset the Freakin Counter" %>
  </div>
<% end %>

app/views/counters/edit.html.erb
<h1>Editing Counter</h1>

<%= render 'form' %>

<%= link_to 'Show', @counter %> |
<%= link_to 'Back', counters_path %>

app/views/counters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container" style="padding-top: 2em;">
  <div class="page-header text-center">
    <h1>Days Since Last <small>"Hi, I'm Ryan Deiss"</small></h1>
  </div>

  <div class="text-center">
    <div style="font-size: 200px; color: red;">
      <%= @days_since %>
    </div>
    <div>
      <%= render 'form' %>
    </div>
  </div>
</div>



<!-- <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counters.each do |counter| %>
      <tr>
        <td><%= link_to 'Show', counter %></td>
        <td><%= link_to 'Edit', edit_counter_path(counter) %></td>
        <td><%= link_to 'Destroy', counter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<!-- <br> -->

<!-- <%= link_to 'New Counter', new_counter_path %> -->

app/views/counters/new.html.erb
<!-- <h1>Reset Counter</h1> -->

<%= render 'form' %>

<%= link_to 'Back', counters_path %>

app/views/counters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_counter_path(@counter) %> |
<%= link_to 'Back', counters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RyanCounter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>